name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: "yarn"
      - name: Install Yarn
        run: corepack enable |
          corepack prepare yarn@3.3.1 --activate
      - run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Do Format
        if: always()
        run: yarn format
      - name: Check Format
        if: always()
        run: yarn checkFormat
      - name: Update App Version
        run: yarn version patch
      - name: Build
        if: always()
        run: yarn build
