name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: "yarn"
      - name: Install Yarn
        run: corepack enable |
          corepack prepare yarn@3.3.1 --activate
      - run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Format
        if: always()
        run: yarn run checkFormat
      - name: Build
        if: always()
        run: yarn run build
      - name: Update App Version
        run: npm version patch
